# Generated by Django 3.2.9 on 2021-11-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0003_variation_variation_value'),
        ('brands', '0003_alter_brand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_offer', models.PositiveBigIntegerField(help_text='Offer in percentage')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_offer', models.PositiveBigIntegerField(help_text='Offer in percentage')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='BrandOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_offer', models.PositiveBigIntegerField(help_text='Offer in percentage')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
        ),
    ]
