# Generated by Django 3.2.9 on 2021-11-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_delete_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
