# Generated by Django 3.2.9 on 2021-11-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211123_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
