# Generated by Django 3.2.9 on 2021-12-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out of Delivery', 'Out of Delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='tracking_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
