# Generated by Django 3.2.9 on 2021-11-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
